classdef model < ModelClass
    methods
        function [self] = model()
            % Variables
            self.addVariable( ...
                VariableClass('x1') ...
                );
            self.addVariable( ...
                VariableClass('x2') ...
                );
            self.addVariable( ...
                VariableClass('x3') ...
                );

            
            % Parameter
            self.addParameter( ...
                ParameterClass('k1') ...
                );
            self.addParameter( ...
                ParameterClass('k2') ...
                );
            self.addParameter( ...
                ParameterClass('k3') ...
                );
            self.addParameter( ...
                ParameterClass('d1') ...
                );
            self.addParameter( ...
                ParameterClass('d2') ...
                );
            self.addParameter( ...
                ParameterClass('d3') ...
                );
            self.addParameter( ...
                ParameterClass('gamma12') ...
                );
            
            % Equations
            self.addEquation( ...
                EquationClass('d_x1 ==  + k1 - gamma12*x1*x2 - d1*x1') ...
                );
            self.addEquation( ...
                EquationClass('d_x2 ==  + k2*x3 - gamma12*x1*x2 - d2*x2') ...
                );
            self.addEquation( ...
                EquationClass('d_x3 ==  + k3*x1 - d3*x3') ...
                );

        end
    end
end
