function [dxdt] =  modelOdeFun(t,x,p)
%% MODELODEFUN Function that evaluates the ODEs of model.
% This function was autogenerated by the SimulationClass.
%
% param: t Current time in the simulation.
%      : x Vector with states values.
%      : p Struct with the parameters.
%
% return: dxdt Vector with derivatives values.

% States
% x(1,:) = x1
% x(2,:) = x2
% x(3,:) = x3
% x(4,:) = ref	 % (Algebraic state)

% der(x1) (No negative)
dxdt(1,1) = p.k1-p.d1.*x(1,:)-p.gamma12.*x(1,:).*x(2,:);

% Check if the state tries to be negative.
if x(1,1) <= 0.0 && dxdt(1,1) <= 0.0
	dxdt(1,1) = 0.0;
end

% der(x2) (No negative)
dxdt(2,1) = -p.d2.*x(2,:)+p.k2.*x(3,:)-p.gamma12.*x(1,:).*x(2,:);

% Check if the state tries to be negative.
if x(2,1) <= 0.0 && dxdt(2,1) <= 0.0
	dxdt(2,1) = 0.0;
end

% der(x3) (No negative)
dxdt(3,1) = -p.d3.*x(3,:)+p.k3.*x(1,:);

% Check if the state tries to be negative.
if x(3,1) <= 0.0 && dxdt(3,1) <= 0.0
	dxdt(3,1) = 0.0;
end

% der(ref) (Algebraic state)
dxdt(4,1) = -x(4,:)+p.k3./p.d3;

end