function [out] =  model_der(t,x,p)
% Autogenerated function that evaluates the ODEs of the model model.

% States
% x(1,:) = x1
% x(2,:) = x2
% x(3,:) = x3

% der(x1)
out(1,1) = p.k1-p.d1.*x(1,:)-p.gamma12.*x(1,:).*x(2,:);

% der(x2)
out(2,1) = -p.d2.*x(2,:)+p.k2.*x(3,:)-p.gamma12.*x(1,:).*x(2,:);

% der(x3)
out(3,1) = -p.d3.*x(3,:)+p.k3.*x(1,:);

end